update Item SET timevalue = 0 where id = 204 
update Item SET timevalue = 0 where id = 205 
update Item SET timevalue = 0 where id = 211 
update Item SET timevalue = 0 where id = 212 
update Item SET timevalue = 10.81 where id = 213 
update Item SET timevalue = 20.0 where id = 219 
update Item SET timevalue = 0 where id = 220 
update Item SET timevalue = 0 where id = 223 
update Item SET timevalue = 0 where id = 225 
update Item SET timevalue = 0 where id = 226 
update Item SET timevalue = 0 where id = 227 
update Item SET timevalue = 0 where id = 229 
update Item SET timevalue = 0 where id = 230 
update Item SET timevalue = 0 where id = 231 
update Item SET timevalue = 0 where id = 236 
update Item SET timevalue = 0 where id = 238 
update Item SET timevalue = 0 where id = 239 
update Item SET timevalue = 0 where id = 240 
update Item SET timevalue = 0 where id = 242 
update Item SET timevalue = 0 where id = 244 
update Item SET timevalue = 0 where id = 247 
update Item SET timevalue = 0 where id = 249 
update Item SET timevalue = 0 where id = 250 
update Item SET timevalue = 0 where id = 251 
update Item SET timevalue = 5.78 where id = 252 
update Item SET timevalue = 0 where id = 254 
update Item SET timevalue = 0 where id = 257 
update Item SET timevalue = 0 where id = 259 
update Item SET timevalue = 0 where id = 263 
update Item SET timevalue = 0 where id = 264 
update Item SET timevalue = 5.54 where id = 265 
update Item SET timevalue = 0 where id = 267 
update Item SET timevalue = 9.58 where id = 268 
update Item SET timevalue = 0 where id = 270 
update Item SET timevalue = 0 where id = 274 
update Item SET timevalue = 0 where id = 276 
update Item SET timevalue = 0 where id = 277 
update Item SET timevalue = 0 where id = 283 
update Item SET timevalue = 0 where id = 284 
update Item SET timevalue = 0 where id = 287 
update Item SET timevalue = 7.75 where id = 290 
update Item SET timevalue = 58.25 where id = 291 
update Item SET timevalue = 0 where id = 292 
update Item SET timevalue = 0 where id = 293 
update Item SET timevalue = 0 where id = 294 
update Item SET timevalue = 0 where id = 296 
update Item SET timevalue = 0 where id = 299 
update Item SET timevalue = 0 where id = 300 
update Item SET timevalue = 0 where id = 301 
update Item SET timevalue = 0 where id = 302 
