update Item SET timevalue = 0 where id = 204 
update Item SET timevalue = 0 where id = 205 
update Item SET timevalue = 0 where id = 211 
update Item SET timevalue = 0 where id = 212 
update Item SET timevalue = 10.81 where id = 213 
update Item SET timevalue = 20.0 where id = 219 
update Item SET timevalue = 0 where id = 220 
update Item SET timevalue = 0 where id = 223 
update Item SET timevalue = 0 where id = 225 
update Item SET timevalue = 0 where id = 226 
update Item SET timevalue = 0 where id = 227 
update Item SET timevalue = 0 where id = 229 
update Item SET timevalue = 0 where id = 230 
update Item SET timevalue = 0 where id = 231 
update Item SET timevalue = 0 where id = 236 
update Item SET timevalue = 0 where id = 238 
update Item SET timevalue = 0 where id = 239 
update Item SET timevalue = 0 where id = 240 
update Item SET timevalue = 0 where id = 242 
update Item SET timevalue = 0 where id = 244 
update Item SET timevalue = 0 where id = 247 
update Item SET timevalue = 0 where id = 249 
update Item SET timevalue = 0 where id = 250 
update Item SET timevalue = 0 where id = 251 
update Item SET timevalue = 5.78 where id = 252 
update Item SET timevalue = 0 where id = 254 
update Item SET timevalue = 0 where id = 257 
update Item SET timevalue = 0 where id = 259 
update Item SET timevalue = 0 where id = 263 
update Item SET timevalue = 0 where id = 264 
update Item SET timevalue = 5.54 where id = 265 
update Item SET timevalue = 0 where id = 267 
update Item SET timevalue = 9.58 where id = 268 
update Item SET timevalue = 0 where id = 270 
update Item SET timevalue = 0 where id = 274 
update Item SET timevalue = 0 where id = 276 
update Item SET timevalue = 0 where id = 277 
update Item SET timevalue = 0 where id = 283 
update Item SET timevalue = 0 where id = 284 
update Item SET timevalue = 0 where id = 287 
update Item SET timevalue = 7.75 where id = 290 
update Item SET timevalue = 58.25 where id = 291 
update Item SET timevalue = 0 where id = 292 
update Item SET timevalue = 0 where id = 293 
update Item SET timevalue = 0 where id = 294 
update Item SET timevalue = 0 where id = 296 
update Item SET timevalue = 0 where id = 299 
update Item SET timevalue = 0 where id = 300 
update Item SET timevalue = 0 where id = 301 
update Item SET timevalue = 0 where id = 302 
update Item SET timevalue = 0 where id = 303 
update Item SET timevalue = 0 where id = 305 
update Item SET timevalue = 0 where id = 308 
update Item SET timevalue = 0 where id = 309 
update Item SET timevalue = 0 where id = 310 
update Item SET timevalue = 0 where id = 311 
update Item SET timevalue = 0 where id = 312 
update Item SET timevalue = 0 where id = 313 
update Item SET timevalue = 0 where id = 324 
update Item SET timevalue = 0 where id = 325 
update Item SET timevalue = 0 where id = 327 
update Item SET timevalue = 0 where id = 334 
update Item SET timevalue = 0 where id = 335 
update Item SET timevalue = 0 where id = 336 
update Item SET timevalue = 0 where id = 337 
update Item SET timevalue = 0.95 where id = 345 
update Item SET timevalue = 0 where id = 346 
update Item SET timevalue = 21.67 where id = 348 
update Item SET timevalue = 2.36 where id = 349 
update Item SET timevalue = 3.5 where id = 351 
update Item SET timevalue = 0 where id = 353 
update Item SET timevalue = 0 where id = 354 
update Item SET timevalue = 0 where id = 355 
update Item SET timevalue = 0 where id = 356 
update Item SET timevalue = 0 where id = 357 
update Item SET timevalue = 1.9 where id = 358 
update Item SET timevalue = 0 where id = 360 
update Item SET timevalue = 0.39 where id = 361 
update Item SET timevalue = 2.11 where id = 363 
update Item SET timevalue = 0 where id = 364 
update Item SET timevalue = 0 where id = 366 
update Item SET timevalue = 0 where id = 367 
update Item SET timevalue = 0 where id = 368 
update Item SET timevalue = 14.08 where id = 369 
update Item SET timevalue = 0 where id = 374 
update Item SET timevalue = 0 where id = 379 
update Item SET timevalue = 0 where id = 380 
update Item SET timevalue = 0 where id = 383 
update Item SET timevalue = 8.41 where id = 384 
update Item SET timevalue = 0 where id = 385 
update Item SET timevalue = 0 where id = 386 
update Item SET timevalue = 0 where id = 388 
update Item SET timevalue = 0 where id = 389 
update Item SET timevalue = 0.79 where id = 390 
update Item SET timevalue = 0 where id = 392 
update Item SET timevalue = 0 where id = 393 
update Item SET timevalue = 0 where id = 394 
update Item SET timevalue = 0 where id = 395 
update Item SET timevalue = 0 where id = 397 
update Item SET timevalue = 0 where id = 399 
