update Item_Category SET timevalue = 1.99 where name = 1 
update Item_Category SET timevalue = 1.88 where name = 2 
update Item_Category SET timevalue = 2.43 where name = 3 
update Item_Category SET timevalue = 2.19 where name = 4 
update Item_Category SET timevalue = 2.89 where name = 5 
update Item_Category SET timevalue = 0.66 where name = 6 
update Item_Category SET timevalue = 5.94 where name = 10 
update Item_Category SET timevalue = 12.55 where name = 11 
update Item_Category SET timevalue = 4.73 where name = 13 
update Item_Category SET timevalue = 2.48 where name = 14 
update Item_Category SET timevalue = 13.67 where name = 15 
update Item_Category SET timevalue = 1.18 where name = 16 
update Item_Category SET timevalue = 2.15 where name = 17 
update Item_Category SET timevalue = 1.84 where name = 18 
update Item_Category SET timevalue = 4.19 where name = 20 
update Item_Category SET timevalue = 1.67 where name = 21 
update Item_Category SET timevalue = 0.82 where name = 23 
update Item_Category SET timevalue = 15.33 where name = 29 
update Item_Category SET timevalue = 0.12 where name = 60 
update Item_Category SET timevalue = 1.32 where name = 61 
update Item_Category SET timevalue = 0.83 where name = 62 
update Item_Category SET timevalue = 15.33 where name = 79 
update Item_Category SET timevalue = 11.67 where name = 80 
update Item_Category SET timevalue = 1 where name = 81 
update Item_Category SET timevalue = 1 where name = 82 
update Item_Category SET timevalue = 1 where name = 89 
update Item_Category SET timevalue = 1 where name = 90 
update Item_Category SET timevalue = 1 where name = 91 
update Item_Category SET timevalue = 1 where name = 92 
update Item_Category SET timevalue = 1 where name = 93 
update Item_Category SET timevalue = 1 where name = 94 
