update Item_Category SET timevalue = 2.21 where name = 1 
update Item_Category SET timevalue = 1.79 where name = 2 
update Item_Category SET timevalue = 3.12 where name = 3 
update Item_Category SET timevalue = 2.01 where name = 4 
update Item_Category SET timevalue = 3.38 where name = 5 
update Item_Category SET timevalue = 0.82 where name = 6 
update Item_Category SET timevalue = 7.62 where name = 10 
update Item_Category SET timevalue = 9.4 where name = 11 
update Item_Category SET timevalue = 4.62 where name = 13 
update Item_Category SET timevalue = 1.88 where name = 14 
update Item_Category SET timevalue = 2.7 where name = 15 
update Item_Category SET timevalue = 1.3 where name = 16 
update Item_Category SET timevalue = 2.37 where name = 17 
update Item_Category SET timevalue = 3.99 where name = 18 
update Item_Category SET timevalue = 4.21 where name = 20 
update Item_Category SET timevalue = 1.46 where name = 21 
update Item_Category SET timevalue = 0.8 where name = 23 
update Item_Category SET timevalue = 19.5 where name = 29 
update Item_Category SET timevalue = 0.12 where name = 60 
update Item_Category SET timevalue = 1.35 where name = 61 
update Item_Category SET timevalue = 0.52 where name = 62 
update Item_Category SET timevalue = 19.5 where name = 79 
update Item_Category SET timevalue = 1 where name = 80 
update Item_Category SET timevalue = 1 where name = 81 
update Item_Category SET timevalue = 1 where name = 82 
update Item_Category SET timevalue = 1 where name = 89 
update Item_Category SET timevalue = 1 where name = 90 
update Item_Category SET timevalue = 1 where name = 91 
update Item_Category SET timevalue = 1 where name = 92 
update Item_Category SET timevalue = 1 where name = 93 
update Item_Category SET timevalue = 1 where name = 94 
